#!/bin/bash
# 🔍 HACS Debugging Script

echo "🔍 HACS DEBUGGING HILFE"
echo "======================="
echo ""
echo "1️⃣ Home Assistant Logs prüfen:"
echo "   Einstellungen → System → Protokolle"
echo "   Suche nach 'hacs' oder 'custom_components'"
echo ""
echo "2️⃣ HACS Debug-Modus aktivieren:"
echo "   Füge in configuration.yaml hinzu:"
echo ""
echo "   logger:"
echo "     default: info"
echo "     logs:"
echo "       custom_components.hacs: debug"
echo ""
echo "3️⃣ HACS neu laden:"
echo "   HACS → Drei-Punkte-Menü → Reload"
echo "   Oder Home Assistant komplett neu starten"
echo ""
echo "4️⃣ Browser-Cache leeren:"
echo "   Strg+Shift+R für Hard Refresh"
echo "   Oder Inkognito-Modus testen"
echo ""
echo "5️⃣ Repository-Status prüfen:"
echo "   https://github.com/bimberle/ha-stundenplan-card"
echo "   - Release v1.0.4 vorhanden?"
echo "   - Asset ha-stundenplan-card.js hochgeladen?"
echo ""
echo "6️⃣ HACS Repository-Liste aktualisieren:"
echo "   HACS → Drei-Punkte-Menü → Custom repositories"
echo "   → Repository neu hinzufügen mit Kategorie 'Lovelace'"
echo ""
echo "📋 CHECKLISTE FÜR ERFOLGREICHE HACS INSTALLATION:"
echo "   ✅ GitHub Release v1.0.4 erstellt"
echo "   ✅ ha-stundenplan-card.js als Asset hochgeladen"
echo "   ✅ hacs.json mit name: 'Stundenplan Card'"
echo "   ✅ Kategorie 'Lovelace' in HACS gewählt"
echo "   ✅ 10+ Minuten gewartet"
echo ""
echo "💡 TIPP: Falls gar nichts hilft:"
echo "   Erstelle Issue auf GitHub mit Screenshots der HACS-Fehlermeldungen"